receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  # Exporta traces para o Jaeger via gRPC
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  
  # Expoe um endpoint para o Prometheus coletar as metricas
  prometheus:
    endpoint: "0.0.0.0:8889"

  debug:
    verbosity: detailed

  # NOVO: Exportador nativo OTLP via HTTP apontando para o Loki
  otlphttp/loki:
    endpoint: "http://loki:3100/otlp"

service:
  pipelines:
    traces: # salva traces da api
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger]
    metrics: # salva metricas da api
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    logs: # salva logs da api
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlphttp/loki]